# For more information: https://laravel.com/docs/sail
version: '3'
services:
  application:
    container_name: invoices
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - invoices
    depends_on:
      - database
      - cache
  database:
    container_name: invoices_database
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'invoices_database:/var/lib/mysql'
    networks:
      - invoices
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
  cache:
    container_name: invoices_cache
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'invoices_cache:/data'
    networks:
      - invoices
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  mail:
    container_name: invoices_mail
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - invoices
networks:
  invoices:
    driver: bridge
volumes:
  invoices_database:
    driver: local
  invoices_cache:
    driver: local
